# Site Specific Configuration
name: barrydillon
description: personal website
url: https://bmdillon.github.io
author: bmdillon
timezone: Europe/Dublin
timezone_short: ET

# Keywords
keywords: ['seo', 'key', 'words']

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

# Exclusions
exclude: [ 'README.md', 'COPYING', 'vendor' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

